[tasks.build.client.install]
cmd = ["pnpm", "install"]

[tasks.build.client.build]
cmd = ["pnpm", "client-web:build"]

[tasks.build.linux]
cmd = ["cargo", "build", "--release", "--target", "x86_64-unknown-linux-gnu"]

[tasks.build.windows]
cmd = ["cargo", "build", "--release", "--target", "x86_64-pc-windows-gnu"]

# [tasks.clean]
# cmd = ["cargo clean"]

# [tasks.dev.setup]
# deps = ["clean"]
# cmd = ["cargo build"]

# [tasks.dev.build]
# deps = ["clean"]
# cmd = ["cargo build"]

# [tasks.prod.build]
# deps = ["clean"]
# cmd = ["cargo build --release"]

# [tasks.install]
# deps = ["dev.build", "prod.build"]
# cmd = ["cargo install --path ."]
